<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DoktersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('dokters')->delete();
        
        \DB::table('dokters')->insert(array (
            0 => 
            array (
                'id' => 51,
                'nama' => 'Ahmad Fauzi',
                'gelar_depan' => 'dr.',
                'gelar_belakang' => 'Sp.PD',
                'foto' => NULL,
                'poli_id' => 1,
                'spesialisasi' => 'Penyakit Dalam',
                'pendidikan' => 'S1 Kedokteran Universitas Indonesia
Spesialis Penyakit Dalam FKUI',
                'bio' => 'Dokter spesialis penyakit dalam dengan pengalaman lebih dari 15 tahun di bidang penanganan diabetes, hipertensi, dan penyakit metabolik.',
                'is_active' => true,
                'created_at' => '2026-07-23 10:39:57',
                'updated_at' => '2026-07-23 10:39:57',
                'teramedik_id' => NULL,
            ),
            1 => 
            array (
                'id' => 52,
                'nama' => 'Siti Rahayu',
                'gelar_depan' => 'dr.',
                'gelar_belakang' => 'Sp.OG',
                'foto' => NULL,
                'poli_id' => NULL,
                'spesialisasi' => 'Obstetri & Ginekologi',
                'pendidikan' => 'S1 Kedokteran Universitas Gadjah Mada
Spesialis Obstetri & Ginekologi UGM',
                'bio' => 'Spesialis kandungan berpengalaman dalam penanganan kehamilan risiko tinggi, persalinan normal, dan caesar.',
                'is_active' => true,
                'created_at' => '2026-07-23 10:39:57',
                'updated_at' => '2026-07-23 10:39:57',
                'teramedik_id' => NULL,
            ),
            2 => 
            array (
                'id' => 53,
                'nama' => 'Budi Santoso',
                'gelar_depan' => 'dr.',
                'gelar_belakang' => 'Sp.A',
                'foto' => NULL,
                'poli_id' => NULL,
                'spesialisasi' => 'Anak',
                'pendidikan' => 'S1 Kedokteran Universitas Airlangga
Spesialis Anak UNAIR',
                'bio' => 'Dokter spesialis anak yang berdedikasi dalam penanganan tumbuh kembang, gizi, dan penyakit infeksi pada anak.',
                'is_active' => true,
                'created_at' => '2026-07-23 10:39:57',
                'updated_at' => '2026-07-23 10:39:57',
                'teramedik_id' => NULL,
            ),
            3 => 
            array (
                'id' => 54,
                'nama' => 'Dewi Kusumawati',
                'gelar_depan' => 'dr.',
                'gelar_belakang' => 'Sp.JP',
                'foto' => NULL,
                'poli_id' => NULL,
                'spesialisasi' => 'Jantung & Pembuluh Darah',
                'pendidikan' => 'S1 Kedokteran Universitas Diponegoro
Spesialis Jantung & Pembuluh Darah UNDIP',
                'bio' => 'Spesialis jantung dengan keahlian dalam diagnosis dan tatalaksana penyakit jantung koroner, gagal jantung, dan aritmia.',
                'is_active' => true,
                'created_at' => '2026-07-23 10:39:57',
                'updated_at' => '2026-07-23 10:39:57',
                'teramedik_id' => NULL,
            ),
            4 => 
            array (
                'id' => 55,
                'nama' => 'Eko Prasetyo',
                'gelar_depan' => 'dr.',
                'gelar_belakang' => 'Sp.B',
                'foto' => NULL,
                'poli_id' => 16,
                'spesialisasi' => 'Bedah Umum',
                'pendidikan' => 'S1 Kedokteran Universitas Brawijaya
Spesialis Bedah Umum UB',
                'bio' => 'Dokter bedah umum berpengalaman dalam operasi laparoskopi, appendektomi, hernioplasti, dan bedah digestif.',
                'is_active' => true,
                'created_at' => '2026-07-23 10:39:57',
                'updated_at' => '2026-07-23 10:39:57',
                'teramedik_id' => NULL,
            ),
            5 => 
            array (
                'id' => 56,
                'nama' => 'Fitriani Nurdiani',
                'gelar_depan' => 'dr.',
                'gelar_belakang' => 'Sp.S',
                'foto' => NULL,
                'poli_id' => NULL,
            'spesialisasi' => 'Neurologi (Saraf)',
                'pendidikan' => 'S1 Kedokteran Universitas Hasanuddin
Spesialis Neurologi UNHAS',
                'bio' => 'Spesialis saraf dengan fokus pada penanganan stroke, epilepsi, migrain, dan penyakit neurodegeneratif.',
                'is_active' => true,
                'created_at' => '2026-07-23 10:39:57',
                'updated_at' => '2026-07-23 10:39:57',
                'teramedik_id' => NULL,
            ),
            6 => 
            array (
                'id' => 57,
                'nama' => 'Gunawan Hidayat',
                'gelar_depan' => 'dr.',
                'gelar_belakang' => 'Sp.M',
                'foto' => NULL,
                'poli_id' => 11,
                'spesialisasi' => 'Mata',
                'pendidikan' => 'S1 Kedokteran Universitas Padjadjaran
Spesialis Mata UNPAD',
                'bio' => 'Spesialis mata berpengalaman dalam penanganan katarak, glaukoma, kelainan refraksi, dan penyakit retina.',
                'is_active' => true,
                'created_at' => '2026-07-23 10:39:57',
                'updated_at' => '2026-07-23 10:39:57',
                'teramedik_id' => NULL,
            ),
            7 => 
            array (
                'id' => 58,
                'nama' => 'Hendra Wijaya',
                'gelar_depan' => 'dr.',
                'gelar_belakang' => 'Sp.THT-KL',
                'foto' => NULL,
                'poli_id' => 10,
                'spesialisasi' => 'THT-KL',
                'pendidikan' => 'S1 Kedokteran Universitas Sebelas Maret
Spesialis THT-KL UNS',
                'bio' => 'Dokter spesialis THT-KL dengan keahlian dalam penanganan sinusitis, tonsilitis, gangguan pendengaran, dan tumor kepala-leher.',
                'is_active' => true,
                'created_at' => '2026-07-23 10:39:57',
                'updated_at' => '2026-07-23 10:39:57',
                'teramedik_id' => NULL,
            ),
            8 => 
            array (
                'id' => 59,
                'nama' => 'Indah Permatasari',
                'gelar_depan' => 'dr.',
                'gelar_belakang' => 'Sp.KK',
                'foto' => NULL,
                'poli_id' => 12,
                'spesialisasi' => 'Kulit & Kelamin',
                'pendidikan' => 'S1 Kedokteran Universitas Sam Ratulangi
Spesialis Dermatologi & Venerologi UNSRAT',
                'bio' => 'Spesialis kulit dan kelamin dengan pengalaman dalam penanganan dermatitis, psoriasis, acne, dan penyakit kelamin.',
                'is_active' => true,
                'created_at' => '2026-07-23 10:39:57',
                'updated_at' => '2026-07-23 10:39:57',
                'teramedik_id' => NULL,
            ),
            9 => 
            array (
                'id' => 60,
                'nama' => 'Joko Supriyanto',
                'gelar_depan' => 'dr.',
                'gelar_belakang' => 'Sp.OT',
                'foto' => NULL,
                'poli_id' => 3,
                'spesialisasi' => 'Ortopedi & Traumatologi',
                'pendidikan' => 'S1 Kedokteran Universitas Indonesia
Spesialis Ortopedi & Traumatologi FKUI',
                'bio' => 'Dokter spesialis ortopedi berpengalaman dalam penanganan fraktur, penggantian sendi, skoliosis, dan cedera olahraga.',
                'is_active' => true,
                'created_at' => '2026-07-23 10:39:57',
                'updated_at' => '2026-07-23 10:39:57',
                'teramedik_id' => NULL,
            ),
            10 => 
            array (
                'id' => 61,
                'nama' => 'dr. Jindi Oktora, Sp.A',
                'gelar_depan' => NULL,
                'gelar_belakang' => NULL,
                'foto' => NULL,
                'poli_id' => 22,
                'spesialisasi' => NULL,
                'pendidikan' => NULL,
                'bio' => NULL,
                'is_active' => true,
                'created_at' => '2026-07-23 10:42:23',
                'updated_at' => '2026-07-23 10:42:23',
                'teramedik_id' => '6023',
            ),
            11 => 
            array (
                'id' => 62,
                'nama' => 'dr. Santi Gunarwati, Sp. A., M.Kes',
                'gelar_depan' => NULL,
                'gelar_belakang' => NULL,
                'foto' => NULL,
                'poli_id' => 22,
                'spesialisasi' => NULL,
                'pendidikan' => NULL,
                'bio' => NULL,
                'is_active' => true,
                'created_at' => '2026-07-23 10:42:23',
                'updated_at' => '2026-07-23 10:42:23',
                'teramedik_id' => '6024',
            ),
            12 => 
            array (
                'id' => 63,
                'nama' => 'dr. Johan Taruna, Sp.OG',
                'gelar_depan' => NULL,
                'gelar_belakang' => NULL,
                'foto' => NULL,
                'poli_id' => 23,
                'spesialisasi' => NULL,
                'pendidikan' => NULL,
                'bio' => NULL,
                'is_active' => true,
                'created_at' => '2026-07-23 10:42:23',
                'updated_at' => '2026-07-23 10:42:23',
                'teramedik_id' => '6025',
            ),
            13 => 
            array (
                'id' => 64,
                'nama' => 'dr. Ferial Fadhilah, Sp.OG',
                'gelar_depan' => NULL,
                'gelar_belakang' => NULL,
                'foto' => NULL,
                'poli_id' => 23,
                'spesialisasi' => NULL,
                'pendidikan' => NULL,
                'bio' => NULL,
                'is_active' => true,
                'created_at' => '2026-07-23 10:42:23',
                'updated_at' => '2026-07-23 10:42:23',
                'teramedik_id' => '6026',
            ),
            14 => 
            array (
                'id' => 65,
                'nama' => 'dr. Amran Mulyana Alamsyah, Sp.OG',
                'gelar_depan' => NULL,
                'gelar_belakang' => NULL,
                'foto' => NULL,
                'poli_id' => 23,
                'spesialisasi' => NULL,
                'pendidikan' => NULL,
                'bio' => NULL,
                'is_active' => true,
                'created_at' => '2026-07-23 10:42:23',
                'updated_at' => '2026-07-23 10:42:23',
                'teramedik_id' => '6027',
            ),
            15 => 
            array (
                'id' => 66,
                'nama' => 'dr. Roosmalia Ponti, Sp.PD.',
                'gelar_depan' => NULL,
                'gelar_belakang' => NULL,
                'foto' => NULL,
                'poli_id' => 24,
                'spesialisasi' => NULL,
                'pendidikan' => NULL,
                'bio' => NULL,
                'is_active' => true,
                'created_at' => '2026-07-23 10:42:23',
                'updated_at' => '2026-07-23 10:42:23',
                'teramedik_id' => '6003',
            ),
            16 => 
            array (
                'id' => 67,
                'nama' => 'dr. Dikha Dwi Putra, Sp.PD, FINASIM',
                'gelar_depan' => NULL,
                'gelar_belakang' => NULL,
                'foto' => NULL,
                'poli_id' => 24,
                'spesialisasi' => NULL,
                'pendidikan' => NULL,
                'bio' => NULL,
                'is_active' => true,
                'created_at' => '2026-07-23 10:42:23',
                'updated_at' => '2026-07-23 10:42:23',
                'teramedik_id' => '6020',
            ),
            17 => 
            array (
                'id' => 68,
                'nama' => 'dr. Frengki Supriatna, Sp.PD.',
                'gelar_depan' => NULL,
                'gelar_belakang' => NULL,
                'foto' => NULL,
                'poli_id' => 24,
                'spesialisasi' => NULL,
                'pendidikan' => NULL,
                'bio' => NULL,
                'is_active' => true,
                'created_at' => '2026-07-23 10:42:23',
                'updated_at' => '2026-07-23 10:42:23',
                'teramedik_id' => '6021',
            ),
            18 => 
            array (
                'id' => 69,
                'nama' => 'dr. Taufik Gumilar, Sp.B',
                'gelar_depan' => NULL,
                'gelar_belakang' => NULL,
                'foto' => NULL,
                'poli_id' => 25,
                'spesialisasi' => NULL,
                'pendidikan' => NULL,
                'bio' => NULL,
                'is_active' => true,
                'created_at' => '2026-07-23 10:42:23',
                'updated_at' => '2026-07-23 10:42:23',
                'teramedik_id' => '6014',
            ),
            19 => 
            array (
                'id' => 70,
                'nama' => 'dr. Risman Fadjar, Sp.B',
                'gelar_depan' => NULL,
                'gelar_belakang' => NULL,
                'foto' => NULL,
                'poli_id' => 25,
                'spesialisasi' => NULL,
                'pendidikan' => NULL,
                'bio' => NULL,
                'is_active' => true,
                'created_at' => '2026-07-23 10:42:23',
                'updated_at' => '2026-07-23 10:42:23',
                'teramedik_id' => '6019',
            ),
            20 => 
            array (
                'id' => 71,
                'nama' => 'dr. Tessar Lucky Respati, Sp.An',
                'gelar_depan' => NULL,
                'gelar_belakang' => NULL,
                'foto' => NULL,
                'poli_id' => 26,
                'spesialisasi' => NULL,
                'pendidikan' => NULL,
                'bio' => NULL,
                'is_active' => true,
                'created_at' => '2026-07-23 10:42:23',
                'updated_at' => '2026-07-23 10:42:23',
                'teramedik_id' => '6029',
            ),
            21 => 
            array (
                'id' => 72,
                'nama' => 'dr. Fadma Yuliani, Sp.JP',
                'gelar_depan' => NULL,
                'gelar_belakang' => NULL,
                'foto' => NULL,
                'poli_id' => 27,
                'spesialisasi' => NULL,
                'pendidikan' => NULL,
                'bio' => NULL,
                'is_active' => true,
                'created_at' => '2026-07-23 10:42:23',
                'updated_at' => '2026-07-23 10:42:23',
                'teramedik_id' => '5998',
            ),
            22 => 
            array (
                'id' => 73,
                'nama' => 'dr. Ratna Sari Dewi Gill, Sp.JP.,FIHA.,MARS',
                'gelar_depan' => NULL,
                'gelar_belakang' => NULL,
                'foto' => NULL,
                'poli_id' => 27,
                'spesialisasi' => NULL,
                'pendidikan' => NULL,
                'bio' => NULL,
                'is_active' => true,
                'created_at' => '2026-07-23 10:42:23',
                'updated_at' => '2026-07-23 10:42:23',
                'teramedik_id' => '6013',
            ),
            23 => 
            array (
                'id' => 74,
                'nama' => 'dr. Mira Retna Tetiana, Sp.M',
                'gelar_depan' => NULL,
                'gelar_belakang' => NULL,
                'foto' => NULL,
                'poli_id' => 28,
                'spesialisasi' => NULL,
                'pendidikan' => NULL,
                'bio' => NULL,
                'is_active' => true,
                'created_at' => '2026-07-23 10:42:23',
                'updated_at' => '2026-07-23 10:42:23',
                'teramedik_id' => '6010',
            ),
            24 => 
            array (
                'id' => 75,
                'nama' => 'dr. Dwirianti Almira, Sp.M.,M.M',
                'gelar_depan' => NULL,
                'gelar_belakang' => NULL,
                'foto' => NULL,
                'poli_id' => 28,
                'spesialisasi' => NULL,
                'pendidikan' => NULL,
                'bio' => NULL,
                'is_active' => true,
                'created_at' => '2026-07-23 10:42:23',
                'updated_at' => '2026-07-23 10:42:23',
                'teramedik_id' => '8462',
            ),
            25 => 
            array (
                'id' => 76,
                'nama' => 'dr. Aji Kusuma, Sp.T.H.T.B.K.L',
                'gelar_depan' => NULL,
                'gelar_belakang' => NULL,
                'foto' => NULL,
                'poli_id' => 29,
                'spesialisasi' => NULL,
                'pendidikan' => NULL,
                'bio' => NULL,
                'is_active' => true,
                'created_at' => '2026-07-23 10:42:23',
                'updated_at' => '2026-07-23 10:42:23',
                'teramedik_id' => '6007',
            ),
            26 => 
            array (
                'id' => 77,
                'nama' => 'dr. Kresna Hadiputra, Sp.THT',
                'gelar_depan' => NULL,
                'gelar_belakang' => NULL,
                'foto' => NULL,
                'poli_id' => 29,
                'spesialisasi' => NULL,
                'pendidikan' => NULL,
                'bio' => NULL,
                'is_active' => true,
                'created_at' => '2026-07-23 10:42:23',
                'updated_at' => '2026-07-23 10:42:23',
                'teramedik_id' => '6022',
            ),
            27 => 
            array (
                'id' => 78,
                'nama' => 'dr. Angi Yuliani',
                'gelar_depan' => NULL,
                'gelar_belakang' => NULL,
                'foto' => NULL,
                'poli_id' => 30,
                'spesialisasi' => NULL,
                'pendidikan' => NULL,
                'bio' => NULL,
                'is_active' => true,
                'created_at' => '2026-07-23 10:42:23',
                'updated_at' => '2026-07-23 10:42:23',
                'teramedik_id' => '5974',
            ),
            28 => 
            array (
                'id' => 79,
                'nama' => 'dr. Moch Rifqi Rofwana',
                'gelar_depan' => NULL,
                'gelar_belakang' => NULL,
                'foto' => NULL,
                'poli_id' => 30,
                'spesialisasi' => NULL,
                'pendidikan' => NULL,
                'bio' => NULL,
                'is_active' => true,
                'created_at' => '2026-07-23 10:42:23',
                'updated_at' => '2026-07-23 10:42:23',
                'teramedik_id' => '5978',
            ),
            29 => 
            array (
                'id' => 80,
                'nama' => 'dr. Indah Jaka Adhikarsa',
                'gelar_depan' => NULL,
                'gelar_belakang' => NULL,
                'foto' => NULL,
                'poli_id' => 30,
                'spesialisasi' => NULL,
                'pendidikan' => NULL,
                'bio' => NULL,
                'is_active' => true,
                'created_at' => '2026-07-23 10:42:23',
                'updated_at' => '2026-07-23 10:42:23',
                'teramedik_id' => '5980',
            ),
            30 => 
            array (
                'id' => 81,
                'nama' => 'dr. Hary Saktiawan',
                'gelar_depan' => NULL,
                'gelar_belakang' => NULL,
                'foto' => NULL,
                'poli_id' => 30,
                'spesialisasi' => NULL,
                'pendidikan' => NULL,
                'bio' => NULL,
                'is_active' => true,
                'created_at' => '2026-07-23 10:42:23',
                'updated_at' => '2026-07-23 10:42:23',
                'teramedik_id' => '5981',
            ),
            31 => 
            array (
                'id' => 82,
                'nama' => 'dr Arfan Bagja Nugraha',
                'gelar_depan' => NULL,
                'gelar_belakang' => NULL,
                'foto' => NULL,
                'poli_id' => 30,
                'spesialisasi' => NULL,
                'pendidikan' => NULL,
                'bio' => NULL,
                'is_active' => true,
                'created_at' => '2026-07-23 10:42:23',
                'updated_at' => '2026-07-23 10:42:23',
                'teramedik_id' => '5983',
            ),
            32 => 
            array (
                'id' => 83,
                'nama' => 'dr. Iman Teguh Badruzzaman',
                'gelar_depan' => NULL,
                'gelar_belakang' => NULL,
                'foto' => NULL,
                'poli_id' => 30,
                'spesialisasi' => NULL,
                'pendidikan' => NULL,
                'bio' => NULL,
                'is_active' => true,
                'created_at' => '2026-07-23 10:42:23',
                'updated_at' => '2026-07-23 10:42:23',
                'teramedik_id' => '5985',
            ),
            33 => 
            array (
                'id' => 84,
                'nama' => 'dr. Fachri Alfarizi',
                'gelar_depan' => NULL,
                'gelar_belakang' => NULL,
                'foto' => NULL,
                'poli_id' => 30,
                'spesialisasi' => NULL,
                'pendidikan' => NULL,
                'bio' => NULL,
                'is_active' => true,
                'created_at' => '2026-07-23 10:42:23',
                'updated_at' => '2026-07-23 10:42:23',
                'teramedik_id' => '5989',
            ),
            34 => 
            array (
                'id' => 85,
                'nama' => 'dr. Riskah Kartika',
                'gelar_depan' => NULL,
                'gelar_belakang' => NULL,
                'foto' => NULL,
                'poli_id' => 30,
                'spesialisasi' => NULL,
                'pendidikan' => NULL,
                'bio' => NULL,
                'is_active' => true,
                'created_at' => '2026-07-23 10:42:23',
                'updated_at' => '2026-07-23 10:42:23',
                'teramedik_id' => '5990',
            ),
            35 => 
            array (
                'id' => 86,
                'nama' => 'dr. Shalma Destiany Ganar',
                'gelar_depan' => NULL,
                'gelar_belakang' => NULL,
                'foto' => NULL,
                'poli_id' => 30,
                'spesialisasi' => NULL,
                'pendidikan' => NULL,
                'bio' => NULL,
                'is_active' => true,
                'created_at' => '2026-07-23 10:42:23',
                'updated_at' => '2026-07-23 10:42:23',
                'teramedik_id' => '5991',
            ),
            36 => 
            array (
                'id' => 87,
                'nama' => 'dr. Nenggi Nisa Nuraeni',
                'gelar_depan' => NULL,
                'gelar_belakang' => NULL,
                'foto' => NULL,
                'poli_id' => 30,
                'spesialisasi' => NULL,
                'pendidikan' => NULL,
                'bio' => NULL,
                'is_active' => true,
                'created_at' => '2026-07-23 10:42:23',
                'updated_at' => '2026-07-23 10:42:23',
                'teramedik_id' => '5993',
            ),
            37 => 
            array (
                'id' => 88,
                'nama' => 'dr. Pera Anabela Oktavia',
                'gelar_depan' => NULL,
                'gelar_belakang' => NULL,
                'foto' => NULL,
                'poli_id' => 30,
                'spesialisasi' => NULL,
                'pendidikan' => NULL,
                'bio' => NULL,
                'is_active' => true,
                'created_at' => '2026-07-23 10:42:23',
                'updated_at' => '2026-07-23 10:42:23',
                'teramedik_id' => '8495',
            ),
            38 => 
            array (
                'id' => 89,
                'nama' => 'dr. M Farras Afif',
                'gelar_depan' => NULL,
                'gelar_belakang' => NULL,
                'foto' => NULL,
                'poli_id' => 30,
                'spesialisasi' => NULL,
                'pendidikan' => NULL,
                'bio' => NULL,
                'is_active' => true,
                'created_at' => '2026-07-23 10:42:23',
                'updated_at' => '2026-07-23 10:42:23',
                'teramedik_id' => '9421',
            ),
            39 => 
            array (
                'id' => 90,
                'nama' => 'dr. Rizky Sukma Oktaviani',
                'gelar_depan' => NULL,
                'gelar_belakang' => NULL,
                'foto' => NULL,
                'poli_id' => 30,
                'spesialisasi' => NULL,
                'pendidikan' => NULL,
                'bio' => NULL,
                'is_active' => true,
                'created_at' => '2026-07-23 10:42:23',
                'updated_at' => '2026-07-23 10:42:23',
                'teramedik_id' => '9470',
            ),
            40 => 
            array (
                'id' => 91,
                'nama' => 'dr. Maulidatul Hasanah',
                'gelar_depan' => NULL,
                'gelar_belakang' => NULL,
                'foto' => NULL,
                'poli_id' => 30,
                'spesialisasi' => NULL,
                'pendidikan' => NULL,
                'bio' => NULL,
                'is_active' => true,
                'created_at' => '2026-07-23 10:42:23',
                'updated_at' => '2026-07-23 10:42:23',
                'teramedik_id' => '9510',
            ),
            41 => 
            array (
                'id' => 92,
                'nama' => 'dr. Ai Sita Nurain',
                'gelar_depan' => NULL,
                'gelar_belakang' => NULL,
                'foto' => NULL,
                'poli_id' => 30,
                'spesialisasi' => NULL,
                'pendidikan' => NULL,
                'bio' => NULL,
                'is_active' => true,
                'created_at' => '2026-07-23 10:42:23',
                'updated_at' => '2026-07-23 10:42:23',
                'teramedik_id' => '9511',
            ),
            42 => 
            array (
                'id' => 93,
                'nama' => 'dr. Fathimah Hanifah',
                'gelar_depan' => NULL,
                'gelar_belakang' => NULL,
                'foto' => NULL,
                'poli_id' => 30,
                'spesialisasi' => NULL,
                'pendidikan' => NULL,
                'bio' => NULL,
                'is_active' => true,
                'created_at' => '2026-07-23 10:42:23',
                'updated_at' => '2026-07-23 10:42:23',
                'teramedik_id' => '9676',
            ),
            43 => 
            array (
                'id' => 94,
                'nama' => 'drg. Raka Putri Dayataka',
                'gelar_depan' => NULL,
                'gelar_belakang' => NULL,
                'foto' => NULL,
                'poli_id' => 31,
                'spesialisasi' => NULL,
                'pendidikan' => NULL,
                'bio' => NULL,
                'is_active' => true,
                'created_at' => '2026-07-23 10:42:23',
                'updated_at' => '2026-07-23 10:42:23',
                'teramedik_id' => '5994',
            ),
            44 => 
            array (
                'id' => 95,
                'nama' => 'drg. Githa Syah Putri',
                'gelar_depan' => NULL,
                'gelar_belakang' => NULL,
                'foto' => NULL,
                'poli_id' => 31,
                'spesialisasi' => NULL,
                'pendidikan' => NULL,
                'bio' => NULL,
                'is_active' => true,
                'created_at' => '2026-07-23 10:42:23',
                'updated_at' => '2026-07-23 10:42:23',
                'teramedik_id' => '5995',
            ),
            45 => 
            array (
                'id' => 96,
                'nama' => 'drg. Ari Heryadi',
                'gelar_depan' => NULL,
                'gelar_belakang' => NULL,
                'foto' => NULL,
                'poli_id' => 31,
                'spesialisasi' => NULL,
                'pendidikan' => NULL,
                'bio' => NULL,
                'is_active' => true,
                'created_at' => '2026-07-23 10:42:23',
                'updated_at' => '2026-07-23 10:42:23',
                'teramedik_id' => '5996',
            ),
            46 => 
            array (
                'id' => 97,
                'nama' => 'drg. Ika Fitriananingrum',
                'gelar_depan' => NULL,
                'gelar_belakang' => NULL,
                'foto' => NULL,
                'poli_id' => 31,
                'spesialisasi' => NULL,
                'pendidikan' => NULL,
                'bio' => NULL,
                'is_active' => true,
                'created_at' => '2026-07-23 10:42:23',
                'updated_at' => '2026-07-23 10:42:23',
                'teramedik_id' => '5997',
            ),
            47 => 
            array (
                'id' => 98,
                'nama' => 'dr. Robert Martua, Sp.OT',
                'gelar_depan' => NULL,
                'gelar_belakang' => NULL,
                'foto' => NULL,
                'poli_id' => 32,
                'spesialisasi' => NULL,
                'pendidikan' => NULL,
                'bio' => NULL,
                'is_active' => true,
                'created_at' => '2026-07-23 10:42:23',
                'updated_at' => '2026-07-23 10:42:23',
                'teramedik_id' => '6018',
            ),
            48 => 
            array (
                'id' => 99,
                'nama' => 'dr. Meyza Gina Farika, Sp.BA',
                'gelar_depan' => NULL,
                'gelar_belakang' => NULL,
                'foto' => NULL,
                'poli_id' => 33,
                'spesialisasi' => NULL,
                'pendidikan' => NULL,
                'bio' => NULL,
                'is_active' => true,
                'created_at' => '2026-07-23 10:42:23',
                'updated_at' => '2026-07-23 10:42:23',
                'teramedik_id' => '6005',
            ),
            49 => 
            array (
                'id' => 100,
                'nama' => 'dr. Taufiq Nashrulloh, Sp.KFR',
                'gelar_depan' => NULL,
                'gelar_belakang' => NULL,
                'foto' => NULL,
                'poli_id' => 34,
                'spesialisasi' => NULL,
                'pendidikan' => NULL,
                'bio' => NULL,
                'is_active' => true,
                'created_at' => '2026-07-23 10:42:23',
                'updated_at' => '2026-07-23 10:42:23',
                'teramedik_id' => '6006',
            ),
            50 => 
            array (
                'id' => 101,
                'nama' => 'dr. Daruqutni, Sp.U',
                'gelar_depan' => NULL,
                'gelar_belakang' => NULL,
                'foto' => NULL,
                'poli_id' => 35,
                'spesialisasi' => NULL,
                'pendidikan' => NULL,
                'bio' => NULL,
                'is_active' => true,
                'created_at' => '2026-07-23 10:42:23',
                'updated_at' => '2026-07-23 10:42:23',
                'teramedik_id' => '6008',
            ),
            51 => 
            array (
                'id' => 102,
            'nama' => 'drg. Winarno Priyanto, Sp.BMM., Subsp.C.O.M (K)',
                'gelar_depan' => NULL,
                'gelar_belakang' => NULL,
                'foto' => NULL,
                'poli_id' => 36,
                'spesialisasi' => NULL,
                'pendidikan' => NULL,
                'bio' => NULL,
                'is_active' => true,
                'created_at' => '2026-07-23 10:42:23',
                'updated_at' => '2026-07-23 10:42:23',
                'teramedik_id' => '6009',
            ),
            52 => 
            array (
                'id' => 103,
                'nama' => 'dr. Pandu Mahesa, Sp.P',
                'gelar_depan' => NULL,
                'gelar_belakang' => NULL,
                'foto' => NULL,
                'poli_id' => 37,
                'spesialisasi' => NULL,
                'pendidikan' => NULL,
                'bio' => NULL,
                'is_active' => true,
                'created_at' => '2026-07-23 10:42:23',
                'updated_at' => '2026-07-23 10:42:23',
                'teramedik_id' => '5999',
            ),
            53 => 
            array (
                'id' => 104,
                'nama' => 'dr. Hadian Adhipratama, Sp.B.S',
                'gelar_depan' => NULL,
                'gelar_belakang' => NULL,
                'foto' => NULL,
                'poli_id' => 38,
                'spesialisasi' => NULL,
                'pendidikan' => NULL,
                'bio' => NULL,
                'is_active' => true,
                'created_at' => '2026-07-23 10:42:23',
                'updated_at' => '2026-07-23 10:42:23',
                'teramedik_id' => '6017',
            ),
            54 => 
            array (
                'id' => 105,
                'nama' => 'drg. Dikdik Lazuardi Fahrizal, Sp.K.G',
                'gelar_depan' => NULL,
                'gelar_belakang' => NULL,
                'foto' => NULL,
                'poli_id' => 39,
                'spesialisasi' => NULL,
                'pendidikan' => NULL,
                'bio' => NULL,
                'is_active' => true,
                'created_at' => '2026-07-23 10:42:23',
                'updated_at' => '2026-07-23 10:42:23',
                'teramedik_id' => '5979',
            ),
            55 => 
            array (
                'id' => 106,
                'nama' => 'drg. Endiyanto Wahyu Nugroho Sp. Ort',
                'gelar_depan' => NULL,
                'gelar_belakang' => NULL,
                'foto' => NULL,
                'poli_id' => 40,
                'spesialisasi' => NULL,
                'pendidikan' => NULL,
                'bio' => NULL,
                'is_active' => true,
                'created_at' => '2026-07-23 10:42:23',
                'updated_at' => '2026-07-23 10:42:23',
                'teramedik_id' => '7731',
            ),
            56 => 
            array (
                'id' => 107,
                'nama' => 'dr. Intan Arvianty, Sp.DVE',
                'gelar_depan' => NULL,
                'gelar_belakang' => NULL,
                'foto' => NULL,
                'poli_id' => 41,
                'spesialisasi' => NULL,
                'pendidikan' => NULL,
                'bio' => NULL,
                'is_active' => true,
                'created_at' => '2026-07-23 10:42:23',
                'updated_at' => '2026-07-23 10:42:23',
                'teramedik_id' => '6000',
            ),
            57 => 
            array (
                'id' => 108,
                'nama' => 'dr. M Radyn Haryadi Widjaya , Sp.D.V',
                'gelar_depan' => NULL,
                'gelar_belakang' => NULL,
                'foto' => NULL,
                'poli_id' => 41,
                'spesialisasi' => NULL,
                'pendidikan' => NULL,
                'bio' => NULL,
                'is_active' => true,
                'created_at' => '2026-07-23 10:42:23',
                'updated_at' => '2026-07-23 10:42:23',
                'teramedik_id' => '6012',
            ),
            58 => 
            array (
                'id' => 109,
                'nama' => 'dr. Ellina Yustiono, Sp.N',
                'gelar_depan' => NULL,
                'gelar_belakang' => NULL,
                'foto' => NULL,
                'poli_id' => 42,
                'spesialisasi' => NULL,
                'pendidikan' => NULL,
                'bio' => NULL,
                'is_active' => true,
                'created_at' => '2026-07-23 10:42:23',
                'updated_at' => '2026-07-23 10:42:23',
                'teramedik_id' => '6004',
            ),
            59 => 
            array (
                'id' => 110,
                'nama' => 'dr. Lani Satiyani, Sp.N',
                'gelar_depan' => NULL,
                'gelar_belakang' => NULL,
                'foto' => NULL,
                'poli_id' => 42,
                'spesialisasi' => NULL,
                'pendidikan' => NULL,
                'bio' => NULL,
                'is_active' => true,
                'created_at' => '2026-07-23 10:42:23',
                'updated_at' => '2026-07-23 10:42:23',
                'teramedik_id' => '6028',
            ),
        ));
        
        
    }
}