<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Karir;
use Carbon\Carbon;

class KarirSeeder extends Seeder
{
    public function run(): void
    {
        // Hapus data karir lama
        Karir::truncate();

        $data = [
            [
                'posisi' => 'Perawat IGD',
                'departemen' => 'Keperawatan',
                'kategori' => 'Keperawatan',
                'tipe' => 'kontrak',
                'lokasi' => 'Subang, Jawa Barat',
                'kuota' => 1,
                'deskripsi' => '<p><strong>Kualifikasi Khusus:</strong></p><p>Minimal pengalaman di IGD Rumah Sakit 2 tahun</p><p><br></p>',
                'persyaratan' => "Laki-laki / Perempuan\nPendidikan minimal D3 Keperawatan / Profesi Ners (lebih disukai)\nMemiliki STR Aktif\nDiutamakan memiliki pengalaman minimal 1 tahun di Rumah Sakit\nMemiliki sertifikat BTCLS yang masih berlaku\nSehat jasmani dan rohani\nBersedia bergabung segera",
                'batas_lamaran' => null,
                'is_active' => true,
            ],
            [
                'posisi' => 'Perawat Rawat Inap',
                'departemen' => 'Keperawatan',
                'kategori' => 'Keperawatan',
                'tipe' => 'kontrak',
                'lokasi' => 'Subang, Jawa Barat',
                'kuota' => 1,
                'deskripsi' => '<p><strong>Kualifikasi Khusus:</strong></p><p>Pengalaman di Rawat Inap Rumah Sakit 1 tahun</p><p><br></p>',
                'persyaratan' => "Laki-laki / Perempuan\nPendidikan minimal D3 Keperawatan / Profesi Ners (lebih disukai)\nMemiliki STR Aktif\nDiutamakan memiliki pengalaman minimal 1 tahun di Rumah Sakit\nMemiliki sertifikat BTCLS yang masih berlaku\nSehat jasmani dan rohani\nBersedia bergabung segera",
                'batas_lamaran' => null,
                'is_active' => true,
            ],
            [
                'posisi' => 'Apoteker',
                'departemen' => 'Penunjang Medis',
                'kategori' => 'Penunjang Medis',
                'tipe' => 'kontrak',
                'lokasi' => 'Subang, Jawa Barat',
                'kuota' => 1,
                'deskripsi' => '<p>Apoteker di Rumah Sakit Hamori bertugas mengelola penerimaan, penyimpanan, dan pendistribusian sediaan farmasi serta alat kesehatan sesuai standar pelayanan rumah sakit, sekaligus melakukan pengkajian resep, dispensing, Pemberian Informasi Obat (PIO) secara komunikatif, serta mengelola administrasi, rekonsiliasi obat, dan koordinasi layanan farmasi untuk pasien program BPJS (Prolanis).</p>',
                'persyaratan' => "Laki-laki / Perempuan\nPendidikan Profesi Apoteker\nPengalaman minimal 1 tahun di Rumah Sakit (Lebih disukai)\nMemiliki STRA Aktif\nMemahami Prolanis BPJS Lebih disukai\nKomunikatif dan bersedia bergabung segera",
                'batas_lamaran' => null,
                'is_active' => true,
            ],
            [
                'posisi' => 'Dokter Umum',
                'departemen' => 'Pelayanan Medis',
                'kategori' => 'Pelayanan Medis',
                'tipe' => 'part-time',
                'lokasi' => 'Subang, Jawa Barat',
                'kuota' => 1,
                'deskripsi' => '<p>Dokter Umum (Part Time) di Rumah Sakit Hamori bertanggung jawab memberikan pelayanan medis darurat dan konsultasi pasien, melakukan penanganan kegawatdaruratan awal sesuai standar prosedur operasional rumah sakit dengan menerapkan kompetensi ACLS dan ATLS, serta berkolaborasi dengan tim medis untuk memastikan keselamatan dan keandalan pelayanan pasien.</p>',
                'persyaratan' => "Laki-laki / Perempuan\nMemiliki STR aktif\nMemiliki sertifikat pelatihan ACLS dan ATLS\nMinimal pengalaman 1 tahun di Rumah Sakit\nBersedia bergabung segera",
                'batas_lamaran' => null,
                'is_active' => true,
            ],
            [
                'posisi' => 'Perawat ICU',
                'departemen' => 'Keperawatan',
                'kategori' => 'Keperawatan',
                'tipe' => 'kontrak',
                'lokasi' => 'Subang, Jawa Barat',
                'kuota' => 1,
                'deskripsi' => '<p><strong>Kualifikasi Khusus:</strong></p><p>Pengalaman di ICU Rumah Sakit 1 tahun &amp; memiliki sertifikat ICU dasar/komprehensif</p><p><br></p>',
                'persyaratan' => "Laki-laki / Perempuan\nPendidikan minimal D3 Keperawatan / Profesi Ners (lebih disukai)\nMemiliki STR Aktif\nDiutamakan memiliki pengalaman minimal 1 tahun di Rumah Sakit\nMemiliki sertifikat BTCLS yang masih berlaku\nSehat jasmani dan rohani\nBersedia bergabung segera",
                'batas_lamaran' => null,
                'is_active' => true,
            ],
            [
                'posisi' => 'Perawat PICU/NICU',
                'departemen' => 'Keperawatan',
                'kategori' => 'Keperawatan',
                'tipe' => 'kontrak',
                'lokasi' => 'Subang, Jawa Barat',
                'kuota' => 1,
                'deskripsi' => '<p><strong>Kualifikasi Khusus:</strong></p><p>Pengalaman minimal 1 tahun di PICU/NICU/Perina Rumah Sakit &amp; diutamakan memiliki sertifikat Perina dan pelatihan NICU dasar/komprehensif</p>',
                'persyaratan' => "Laki-laki / Perempuan\nPendidikan minimal D3 Keperawatan / Profesi Ners (lebih disukai)\nMemiliki STR Aktif\nDiutamakan memiliki pengalaman minimal 1 tahun di Rumah Sakit\nMemiliki sertifikat BTCLS yang masih berlaku\nSehat jasmani dan rohani\nBersedia bergabung segera",
                'batas_lamaran' => null,
                'is_active' => true,
            ],
            [
                'posisi' => 'Perawat OK',
                'departemen' => 'Keperawatan',
                'kategori' => 'Keperawatan',
                'tipe' => 'kontrak',
                'lokasi' => 'Subang, Jawa Barat',
                'kuota' => 1,
                'deskripsi' => '<p><strong>Kualifikasi Khusus:</strong></p><p>Pengalaman minimal 2 tahun OK &amp; sertifikat perawat bedah</p><p><br></p>',
                'persyaratan' => "Laki-laki / Perempuan\nPendidikan minimal D3 Keperawatan / Profesi Ners (lebih disukai)\nMemiliki STR Aktif\nDiutamakan memiliki pengalaman minimal 1 tahun di Rumah Sakit\nMemiliki sertifikat BTCLS yang masih berlaku\nSehat jasmani dan rohani\nBersedia bergabung segera",
                'batas_lamaran' => null,
                'is_active' => true,
            ],
            [
                'posisi' => 'Fisioterapis',
                'departemen' => 'Penunjang Medis',
                'kategori' => 'Penunjang Medis',
                'tipe' => 'kontrak',
                'lokasi' => 'Subang, Jawa Barat',
                'kuota' => 1,
                'deskripsi' => '<p>Fisioterapis di Rumah Sakit Hamori bertanggung jawab memberikan pelayanan rehabilitasi medik yang komprehensif, melakukan asesmen dan penanganan pemulihan fungsi gerak pasien sesuai standar operasional prosedur rumah sakit, serta menjalin komunikasi yang baik dan bekerja sama secara profesional dengan tim medis untuk mendukung proses penyembuhan pasien.</p>',
                'persyaratan' => "Laki-laki / Perempuan\nPendidikan minimal D3 Fisioterapi\nMemiliki STR aktif\nBerpengalaman di bidang yang sama minimal 1 tahun di Rumah Sakit\nMemiliki komunikasi yang baik\nDapat bekerja sama dengan tim",
                'batas_lamaran' => null,
                'is_active' => true,
            ],
            [
                'posisi' => 'Terapis Wicara',
                'departemen' => 'Penunjang Medis',
                'kategori' => 'Penunjang Medis',
                'tipe' => 'kontrak',
                'lokasi' => 'Subang, Jawa Barat',
                'kuota' => 1,
                'deskripsi' => '<p>Terapis Wicara di Rumah Sakit Hamori bertanggung jawab memberikan pelayanan terapi dan pemulihan gangguan komunikasi, bahasa, serta bicara pasien secara komprehensif, melakukan asesmen dan penanganan sesuai standar operasional prosedur rumah sakit, serta menjalin komunikasi yang baik dan bekerja sama secara profesional dengan tim medis untuk mengoptimalkan proses pemulihan pasien.</p>',
                'persyaratan' => "Laki-laki / Perempuan\nPendidikan minimal D3 Terapis Wicara\nMemiliki STR aktif\nBerpengalaman di bidang yang sama minimal 1 tahun di Rumah Sakit\nMemiliki komunikasi yang baik\nDapat bekerja sama dengan tim",
                'batas_lamaran' => null,
                'is_active' => true,
            ],
            [
                'posisi' => 'Terapis Okupasi',
                'departemen' => 'Penunjang Medis',
                'kategori' => 'Penunjang Medis',
                'tipe' => 'kontrak',
                'lokasi' => 'Subang, Jawa Barat',
                'kuota' => 1,
                'deskripsi' => '<p>Terapis Okupasi di Rumah Sakit Hamori bertanggung jawab memberikan pelayanan rehabilitasi dan pemulihan fungsi motorik maupun kognitif pasien agar dapat kembali mandiri dalam aktivitas sehari-hari, melakukan asesmen serta intervensi terapi sesuai standar operasional prosedur rumah sakit, serta menjalin komunikasi yang efektif dan bekerja sama secara profesional dengan tim medis untuk mendukung pencapaian hasil perawatan pasien yang optimal.</p>',
                'persyaratan' => "Laki-laki / Perempuan\nPendidikan minimal D3 Okupasi Terapi\nMemiliki STR aktif\nBerpengalaman di bidang yang sama minimal 1 tahun di Rumah Sakit\nMemiliki komunikasi yang baik\nDapat bekerja sama dengan tim",
                'batas_lamaran' => null,
                'is_active' => true,
            ],
            [
                'posisi' => 'Fisioterapis',
                'departemen' => 'Rehabilitasi Medik',
                'kategori' => 'Penunjang Medis',
                'tipe' => 'full-time',
                'lokasi' => 'Subang',
                'kuota' => 1,
                'deskripsi' => 'Memberikan pelayanan fisioterapi komprehensif kepada pasien dengan gangguan muskuloskeletal, neurologis, dan kardiopulmonal.',
                'persyaratan' => "- D3/D4/S1 Fisioterapi, STR aktif\n- Pengalaman minimal 1 tahun\n- Sabar dan empatik",
                'batas_lamaran' => '2026-09-15',
                'is_active' => true,
            ],
            [
                'posisi' => 'Bidan PONEK',
                'departemen' => 'Kebidanan dan Kandungan',
                'kategori' => 'Pelayanan Medis',
                'tipe' => 'kontrak',
                'lokasi' => 'Subang, Jawa Barat',
                'kuota' => 1,
                'deskripsi' => '<p>Bidan di Rumah Sakit Hamori bertanggung jawab memberikan pelayanan asuhan kebidanan secara komprehensif mulai dari masa kehamilan, persalinan, nifas, hingga perawatan kesehatan reproduksi ibu dan bayi, melaksanakan penanganan kegawatdaruratan kebidanan sesuai standar prosedur operasional rumah sakit, serta menjaga komunikasi yang profesional dan kerja sama yang baik dengan tim medis demi menjamin keselamatan dan kenyamanan pasien.</p><p><br></p><p>Kualifikasi Khusus:</p><p>Minimal pengalaman di PONEK Rumah Sakit 1 tahun</p>',
                'persyaratan' => "Perempuan\nPendidikan minimal D3 Kebidanan, Profesi lebih disukai\nMemiliki STR Aktif\nDiutamakan memiliki pengalaman minimal 1 tahun di Rumah Sakit\nMemiliki sertifikat APN & PPGDON yang masih berlaku\nSehat jasmani dan rohani\nBersedia bergabung segera",
                'batas_lamaran' => null,
                'is_active' => true,
            ],
            [
                'posisi' => 'Bidan VK',
                'departemen' => 'Kebidanan dan Kandungan',
                'kategori' => 'Pelayanan Medis',
                'tipe' => 'kontrak',
                'lokasi' => 'Subang, Jawa Barat',
                'kuota' => 1,
                'deskripsi' => '<p>Bidan di Rumah Sakit Hamori bertanggung jawab memberikan pelayanan asuhan kebidanan secara komprehensif mulai dari masa kehamilan, persalinan, nifas, hingga perawatan kesehatan reproduksi ibu dan bayi, melaksanakan penanganan kegawatdaruratan kebidanan sesuai standar prosedur operasional rumah sakit, serta menjaga komunikasi yang profesional dan kerja sama yang baik dengan tim medis demi menjamin keselamatan dan kenyamanan pasien.</p><p><br></p><p>Kualifikasi Khusus:</p><p>Pengalaman minimal 1 tahun VK</p>',
                'persyaratan' => "Perempuan\nPendidikan minimal D3 Kebidanan, Profesi lebih disukai\nMemiliki STR Aktif\nDiutamakan memiliki pengalaman minimal 1 tahun di Rumah Sakit\nMemiliki sertifikat APN & PPGDON yang masih berlaku\nSehat jasmani dan rohani\nBersedia bergabung segera",
                'batas_lamaran' => null,
                'is_active' => true,
            ],
            [
                'posisi' => 'Bidan Rawat Inap',
                'departemen' => 'Kebidanan dan Kandungan',
                'kategori' => 'Pelayanan Medis',
                'tipe' => 'kontrak',
                'lokasi' => 'Subang, Jawa Barat',
                'kuota' => 1,
                'deskripsi' => '<p>Bidan di Rumah Sakit Hamori bertanggung jawab memberikan pelayanan asuhan kebidanan secara komprehensif mulai dari masa kehamilan, persalinan, nifas, hingga perawatan kesehatan reproduksi ibu dan bayi, melaksanakan penanganan kegawatdaruratan kebidanan sesuai standar prosedur operasional rumah sakit, serta menjaga komunikasi yang profesional dan kerja sama yang baik dengan tim medis demi menjamin keselamatan dan kenyamanan pasien.</p><p><br></p><p>Kualifikasi Khusus:</p><p>Pengalaman di Rawat Inap Rumah Sakit 1 tahun</p>',
                'persyaratan' => "Perempuan\nPendidikan minimal D3 Kebidanan, Profesi lebih disukai\nMemiliki STR Aktif\nDiutamakan memiliki pengalaman minimal 1 tahun di Rumah Sakit\nMemiliki sertifikat APN & PPGDON yang masih berlaku\nSehat jasmani dan rohani\nBersedia bergabung segera",
                'batas_lamaran' => null,
                'is_active' => true,
            ],
            [
                'posisi' => 'Rekam Medis',
                'departemen' => 'Penunjang Medis',
                'kategori' => 'Penunjang Medis',
                'tipe' => 'kontrak',
                'lokasi' => 'Subang, Jawa Barat',
                'kuota' => 1,
                'deskripsi' => '<p>Perekam Medis di Rumah Sakit Hamori bertanggung jawab mengelola pencatatan, pengumpulan, pengolahan, serta penyajian data rekam medis pasien secara akurat dan tepat waktu sesuai standar operasional prosedur rumah sakit, melakukan kodifikasi penyakit serta tindakan medis (ICD-10 dan ICD-9-CM), serta menjaga kerahasiaan berkas rekam medis dan berkoordinasi secara profesional dengan unit pelayanan kesehatan lainnya.</p>',
                'persyaratan' => "Laki-laki / Perempuan\nMinimal pendidikan D3 Rekam Medis\nMemiliki STR aktif\nWajib memiliki pengalaman kerja di Instalasi Rekam Medis minimal 1 tahun di Rumah Sakit\nDapat menguasai kodifikasi ICD X dan ICD 9 cm\nMenguasai pelaporan di Rekam Medis\nTerampil menggunakan SIMRS\nDisiplin, jujur, dan dapat bekerja sama baik individu maupun tim",
                'batas_lamaran' => '2026-06-18',
                'is_active' => true,
            ],
            [
                'posisi' => 'Staff Elektromedis / ATEM',
                'departemen' => 'Umum',
                'kategori' => 'Back Office',
                'tipe' => 'kontrak',
                'lokasi' => 'Subang, Jawa Barat',
                'kuota' => 1,
                'deskripsi' => '<p>Staff Elektromedis / ATEM di Rumah Sakit Hamori bertanggung jawab mengelola, memelihara, dan memastikan seluruh peralatan medis berfungsi dengan aman, akurat, serta siap digunakan sesuai standar operasional prosedur rumah sakit, termasuk melakukan instalasi, pengujian fungsi, kalibrasi, serta perbaikan berkala pada alat-alat kesehatan demi mendukung kelancaran pelayanan medis secara keseluruhan.</p>',
                'persyaratan' => "Laki-laki / Perempuan\nPendidikan minimal D3/D4 Teknik Elektromedik (ATEM)\nMemiliki Surat Tanda Registrasi (STR) Aktif\nDiutamakan minimal memiliki pengalaman 1 tahun di Rumah Sakit (Fresh graduate dipersilakan melamar)\nMemahami sistem dan cara kerja peralatan medis\nMampu melakukan instalasi, uji fungsi, kalibrasi, pemeliharaan, dan perbaikan alat",
                'batas_lamaran' => null,
                'is_active' => true,
            ],
            [
                'posisi' => 'Tenaga Teknis Kefarmasian (TTK)',
                'departemen' => 'Penunjang Medis',
                'kategori' => 'Penunjang Medis',
                'tipe' => 'kontrak',
                'lokasi' => 'Subang, Jawa Barat',
                'kuota' => 1,
                'deskripsi' => '<p>Tenaga Teknis Kefarmasian (TTK) di Rumah Sakit Hamori bertanggung jawab membantu Apoteker dalam kegiatan pengelolaan, penerimaan, penyimpanan, dan pendistribusian sediaan farmasi serta alat kesehatan, menyiapkan dan meracik obat sesuai dengan resep secara teliti, serta memastikan ketersediaan stok farmasi berjalan optimal sesuai dengan standar pelayanan kefarmasian rumah sakit.</p>',
                'persyaratan' => "Laki-laki / Perempuan\nPendidikan minimal D3/S1 Farmasi\nMemiliki STRTTK Aktif\nBerpengalaman minimal 1 tahun sebagai Asisten Apoteker di Rumah Sakit\nMemiliki sertifikat yang mendukung (lebih disukai)\nMampu bekerja secara tim dan bersedia bekerja dalam sistem shifting",
                'batas_lamaran' => null,
                'is_active' => true,
            ],
            [
                'posisi' => 'Analis Laboratorium',
                'departemen' => 'Laboratorium Klinik',
                'kategori' => 'Penunjang Medis',
                'tipe' => 'full-time',
                'lokasi' => 'Subang',
                'kuota' => 2,
                'deskripsi' => 'Melakukan pemeriksaan laboratorium klinik meliputi hematologi, kimia darah, urinalisa, dan mikrobiologi.',
                'persyaratan' => "- D3/D4 Analis Kesehatan / Teknologi Laboratorium Medis\n- STR aktif\n- Teliti, terorganisir, dan bertanggung jawab",
                'batas_lamaran' => '2026-09-18',
                'is_active' => true,
            ],
            [
                'posisi' => 'Radiografer',
                'departemen' => 'Radiologi',
                'kategori' => 'Penunjang Medis',
                'tipe' => 'full-time',
                'lokasi' => 'Subang',
                'kuota' => 2,
                'deskripsi' => 'Melakukan pemeriksaan radiologi konvensional, CT-Scan, dan prosedur radiografi sesuai standar proteksi radiasi.',
                'persyaratan' => "- D3/D4 Radiologi, memiliki SIB dan STR aktif\n- Memahami proteksi radiasi\n- Teliti dan bertanggung jawab",
                'batas_lamaran' => '2026-09-25',
                'is_active' => true,
            ],
            [
                'posisi' => 'Apoteker / Asisten Apoteker',
                'departemen' => 'Instalasi Farmasi',
                'kategori' => 'Penunjang Medis',
                'tipe' => 'full-time',
                'lokasi' => 'Subang',
                'kuota' => 3,
                'deskripsi' => 'Melakukan dispensing obat, pelayanan informasi obat, dan farmasi klinik kepada pasien rawat jalan/inap.',
                'persyaratan' => "- S1 Farmasi / Apoteker (STRA aktif) atau D3 Farmasi (STRTTK aktif)\n- Teliti dan jujur\n- Mampu bekerja shift",
                'batas_lamaran' => '2026-09-10',
                'is_active' => true,
            ],
            [
                'posisi' => 'Staff Keuangan & Akuntansi',
                'departemen' => 'Keuangan',
                'kategori' => 'Back Office',
                'tipe' => 'full-time',
                'lokasi' => 'Subang',
                'kuota' => 2,
                'deskripsi' => '<p>Membantu pengelolaan keuangan rumah sakit meliputi pembukuan, laporan keuangan, dan verifikasi tagihan.</p>',
                'persyaratan' => "- S1 Akuntansi / Keuangan\n- Memahami akuntansi dasar\n- Teliti, jujur, dan bertanggung jawab",
                'batas_lamaran' => '2026-09-20',
                'is_active' => true,
            ],
            [
                'posisi' => 'Staff Administrasi Rawat Jalan',
                'departemen' => 'Pendaftaran & Rekam Medis',
                'kategori' => 'Front Office',
                'tipe' => 'full-time',
                'lokasi' => 'Subang',
                'kuota' => 3,
                'deskripsi' => '<p>Melayani pendaftaran pasien rawat jalan, mengelola rekam medis, dan memberikan informasi pelayanan kepada pasien.</p>',
                'persyaratan' => "- D3/S1 semua jurusan (diutamakan Rekam Medis/Manajemen)\n- Ramah, komunikatif, dan sabar\n- Mampu mengoperasikan komputer",
                'batas_lamaran' => '2026-09-12',
                'is_active' => true,
            ],
        ];

        foreach ($data as $item) {
            Karir::create($item);
        }
    }
}
