<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;
use App\Models\KategoriFasilitas;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class KategoriFasilitasController extends Controller
{
    public function index()
    {
        $kategori = KategoriFasilitas::orderBy('urutan')->paginate(10);
        return view('admin.kategori-fasilitas.index', compact('kategori'));
    }

    public function create()
    {
        return view('admin.kategori-fasilitas.form', ['kategori' => null]);
    }

    public function store(Request $request)
    {
        $request->validate([
            'nama' => 'required|string|max:255|unique:kategori_fasilitas',
            'deskripsi' => 'nullable|string',
            'urutan' => 'nullable|integer'
        ]);

        $data = $request->only('nama', 'deskripsi', 'urutan');
        $data['slug'] = Str::slug($request->nama);
        $data['is_active'] = $request->boolean('is_active', true);
        $data['urutan'] = $data['urutan'] ?? 0;

        KategoriFasilitas::create($data);
        return redirect()->route('admin.kategori-fasilitas.index')->with('success', 'Kategori Fasilitas berhasil ditambahkan.');
    }

    public function edit(KategoriFasilitas $kategori_fasilita) // using implicit binding with the name generated by resource
    {
        return view('admin.kategori-fasilitas.form', ['kategori' => $kategori_fasilita]);
    }

    public function update(Request $request, KategoriFasilitas $kategori_fasilita)
    {
        $request->validate([
            'nama' => 'required|string|max:255|unique:kategori_fasilitas,nama,' . $kategori_fasilita->id,
            'deskripsi' => 'nullable|string',
            'urutan' => 'nullable|integer'
        ]);

        $data = $request->only('nama', 'deskripsi', 'urutan');
        $data['slug'] = Str::slug($request->nama);
        $data['is_active'] = $request->boolean('is_active', true);
        $data['urutan'] = $data['urutan'] ?? 0;

        $kategori_fasilita->update($data);
        return redirect()->route('admin.kategori-fasilitas.index')->with('success', 'Kategori Fasilitas berhasil diperbarui.');
    }

    public function destroy(KategoriFasilitas $kategori_fasilita)
    {
        if ($kategori_fasilita->fasilitas()->count() > 0) {
            return back()->with('error', 'Kategori ini tidak bisa dihapus karena masih memiliki fasilitas terkait.');
        }
        $kategori_fasilita->delete();
        return back()->with('success', 'Kategori Fasilitas berhasil dihapus.');
    }

    public function toggleActive(KategoriFasilitas $kategori_fasilita)
    {
        $kategori_fasilita->update(['is_active' => !$kategori_fasilita->is_active]);
        return back()->with('success', 'Status kategori berhasil diperbarui.');
    }
}
